version: '3.8'

services:
  zkramp-locked-indexer:
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
    image: quay.io/apibara/sink-postgres:latest
    command: 'run ./indexer/escrow-locked.indexer.ts --connection-string ${POSTGRES_CONNECTION_STRING} -A ${AUTH_TOKEN}'
    volumes:
      - ./src:/indexer
    networks:
      - indexer
    restart: on-failure

  zkramp-unlocked-indexer:
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
    image: quay.io/apibara/sink-postgres:latest
    command: 'run ./indexer/escrow-unlocked.indexer.ts --connection-string ${POSTGRES_CONNECTION_STRING} -A ${AUTH_TOKEN}'
    volumes:
      - ./src:/indexer
    networks:
      - indexer
    restart: on-failure

networks:
  indexer:
    driver: bridge
