name: Backend

on:
  push:
    paths: [backend/**]
  pull_request:
    paths: [backend/**]

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install
        working-directory: backend

      - name: Check formatting
        run: yarn format:check
        working-directory: backend

      - name: Lint
        run: yarn lint
        working-directory: backend

      - name: Test
        run: yarn test
        working-directory: backend
